### ISSUE TITLE
User can read a list of completed challenges.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#1]
# Motivation

Before submitting relevant JavaScript solutions, users must first be able to submit a coding challenge using a form.

# Tasks

- [x] Configure linters.
- [x] Install and configure essential dependencies:
    - [x] express
    - [x] body-parser
    - [x] dotenv
    - [x] react
    - [x] react-dom
    - [x] redux
    - [x] react-redux
    - [x] styled-components
    - [x] request
- [x] Install and configure essential developer dependencies:
    - [x] browserify
    - [x] watchify
    - [x] babelify
    - [x] nodemon
    - [x] babel-plugin-transform-es2015-modules-commonjs
    - [x] babel-plugin-transform-react-jsx
    - [x] mocha
    - [x] chai
    - [x] nyc
- [x] Create app file structure:
    - [x] Create a server directory with utils sub-directory:
        - [x] Create a Public directory with index.html and styles.css
        - [x] Link stylesheet and import Bootstrap 3
    - [x] Create a client directory with utils sub-directory:
        - [x] Create a main.js file
        - [x] Add an npm script to bundle main.js file into the Public directory on the server
- [x] Create an express server:
    - [x] Use dotenv to house the PORT information in a .env file.
    - [x] Listen on designated port for GET requests.
    - [x] Serve the contents of the Public directory as static middleware.
- [x] Create a redux store for state management:
    - [x] Include list of challenges in state object.
- [x] Create a React smart component to load and render a list of code challenges:
    - [x] Use mapStateToProps to provide component with list of challenges saved in state.
    - [x] Render each challenge using challenge name, author, and difficulty.
- [x] Incorporate testing:
    - [x] Utilize mocha and chai for testing index.js using request

**Comment by danielduffield** [comment]
![codewars-solutions-issue-1](https://user-images.githubusercontent.com/29046343/30006608-dd3e7698-90b0-11e7-8874-73b6175ef7ee.png)
