### ISSUE TITLE
Deploy to Heroku.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#10]
# Motivation

Users can view a demonstration of the app without installation.

# Tasks

- [x] Configure package.json file:
    - [x] Update Node.js to compatible version.
    - [x] Provide Engine property with Node version.
    - [x] Add necessary scripts:
        - [x] postinstall
        - [x] start
