### ISSUE TITLE
Visual Update: Highlight keywords in code snippets.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#12]
# Motivation

To make code snippets more readable, keywords such as var, const, let, function, etc. should be highlighted in a different color.

# Tasks

- [x] Install and save react-syntax-highlighter as a dependency.
- [ ] Refactor rendering of code snippets to use react syntax highlighter rather than HTML insertion.
- [ ] Style code snippets for readability.
