### ISSUE TITLE
Refactor: Build database from solutions stored on server.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#17]
# Motivation

The server should fetch all relevant challenge data from the solution files to automatically populate the database.

# Tasks

- [x] Remove migration files for example entries.
- [x] Create a server utility to build challenge list:
    - [x] Query the database to fetch all existing challenges.
    - [x] Load list of solution files stored on server.
    - [x] Use file name to search Codewars for challenge data.
    - [x] Filter out challenges that already exist in the database by comparing ids.
    - [x] Insert new challenges into database.
    - [x] Add newly inserted challenge ids to list of existing ids.
- [x] Integrate websockets:
    - [x] Install socket.io as a dependency.
    - [x] Create a client socket utility.
    - [x] Create a socket handler for server in index
    - [x] Emit fetchedData to clients on connection
- [x] Load data from previously fetched data:
    - [x] Update fetchedData in state on 'fetchedData' socket event via dispatch
    - [x] Add handler in store for action type 'RECEIVED_FETCHED_DATA'
