### ISSUE TITLE
Users can navigate to sub-pages via hash routing.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#19]
# Motivation

Hash routing will enable users to better navigate to specific sub-pages based on the current view and the selected challenge.

# Tasks

- [x] Build a hash router.
- [x] Create a function to parse valid hash values.
- [x] Dispatch an action to update stored state based on parsed hash values.
