### ISSUE TITLE
User can add a Codewars challenge by submitting the corresponding URL.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#2]
# Motivation

Users should be able to submit a challenge by entering the corresponding Codewars URL.

# Tasks

- [x] Add to store.js:
    - [x] Add view to the state object.
    - [x] Create a handler for dispatch of action.type 'UPDATED_VIEW'.
- [x] Update ChallengeList component:
    - [x] Add a button to the ChallengeList component that dispatches a view update to 'submitForm'
    - [x] Add the view as state to be mapped to props
- [x] Create a React component form for getting URL submissions:
    - [x] Add a button to return to the Challenge List via dispatching a view update to 'challengeList'
    - [x] Use mapStateToProps to pass the view status to the component.
- [x] Add conditionals to React components to only render within the appropriate view.
- [x] Handle URL submission:
    - [x] Add regex pattern match to URL input field.
    - [x] Use regex pattern matching to prevent invalid URL submissions.
    - [x] Create a module that will send a GET request to the URL and scrape the page for relevant data.
    - [x] Update the state of the challenges list to include the newly submitted challenge.
- [x] Add a test for the new Express server POST route

**Comment by danielduffield** [comment]
![codewars-solutions-issue-2](https://user-images.githubusercontent.com/29046343/30289084-ced1378c-96df-11e7-8869-2e8ffe0fa0ce.png)

**Comment by danielduffield** [comment]
![codewars-solutions-issue-2-wireframe](https://user-images.githubusercontent.com/29046343/30290003-d21ba7d0-96e2-11e7-99d0-13e6848485e9.png)
