### ISSUE TITLE
User can showcase a solution to a Codewars problem.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#3]
# Motivation

Users should be able to add solutions to Codewars challenges displayed on the Challenge List.

# Tasks

- [x] Create a React Component called 'SolutionForm' for receiving user Codewars challenge solutions:
    - [x] Create a render condition to display component only when view is "solutionForm"
    - [x] Create a textarea element to receive JavaScript code.
    - [x] Create a button to cancel by triggering a view change to "challengeView".
    - [x] Create a button to submit the solution and return to the "challengeView"
- [x] Update the ChallengeView component:
    - [x] Add a button to trigger a view change to 'solutionForm'

**Comment by danielduffield** [comment]
![codewars-solutions-issue-3-wireframe](https://user-images.githubusercontent.com/29046343/30403707-c899c6ae-9897-11e7-83f7-a50614a5b544.png)

**Comment by danielduffield** [comment]
![codewars-solutions-issue-3-wireframe-new](https://user-images.githubusercontent.com/29046343/30406453-a72bba5e-98a6-11e7-9386-3f0926c3209b.png)
