### ISSUE TITLE
Users can sort challenges by name, author, and difficulty.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#32]
# Motivations

The ability to sort the challenge list will facilitate a better user experience and easier navigation to challenges matching specific criteria.

# Tasks

- [x] Add a property in state to store the currentSort, including properties target and isAscending.
- [x] Add an action handler for type 'SORTED_LIST' to update currentSort property.
- [x] Add a slice and sort to the challengeList render that sorts according to currentSort mapped to props.
