### ISSUE TITLE
User can showcase a solution by loading it from the server.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#5]
# Motivation

Users should be able to easy load solutions from JavaScript files kept on the server file system.

# Tasks

- [x] Add a server utility for reading JavaScript solution files:
    - [x] Import fs to read the JavaScript solution file asynchronously.
    - [x] Send the contents of the file as a response to a client GET request.
- [x] Update the Redux store:
    - [x] Refactor the handler for the 'UPDATED_SELECTED' action type.
- [x] Update the ChallengeList component:
    - [x] Send a GET request using the challenge name as a URL param when a challenge is selected.
    - [x] Change the payload sent with dispatch of 'UPDATED_SELECTED' from selected ID to challenge 
        object with solution.
- [x] Update ChallengeView component:
    - [x] Add a button to"View the Solution" that displays the solution if one exists.
    - [x] Render the button "Submit a Solution" only if no solution exists.
- [x] Update the ChallengeSubmitForm component:
    - [x] Fetch the challenge solution if one exists upon submitting a new challenge.
- [x] Refactor:
    - [x] Change default challenge data to remove description.
    - [x] Fetch both description and solution rather than storing in database.
    - [x] Add a solutionForm property to state to hold the solution form value.
    - [x] Reset the solutionForm when a new challenge is added, a challenge is selected, or a solution is 
        submitted
