### ISSUE TITLE
User can view the details of a challenge.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#6]
# Motivation

In addition to providing links to the actual Codewars page, the app should allow users to read the details of a challenge without leaving the site.

# Tasks

- [x] Update the redux store:
    - [x] Add the challenge description to challenge information saved in state.
    - [x] Change the 'ADDED_CHALLENGE' dispatch to move users from the submit form to the challenge 
        view (from what was previously the challenge list).
    - [x] Add a urlForm property to state for clearing the contents of the url input field on view changes or 
        successful challenge submissions
- [x] Update ChallengeList component:
    - [x] Move hyperlink to Codewars challenge from challenge name to within ChallengeView.
    - [x] Change view to "challengeView" when challenge is selected.
- [x] Update ChallengeSubmitForm component:
    - [x] Convert challenge data from provided markdown to HTML
    - [x] Change the value of the url input form to be read from urlForm mapped from state to props
    - [x] Add an onChange handler to dispatch an action 'UPDATED_URL_FORM'
- [x] Create a React component for displaying an individual challenge called ChallengeView.
    - [x] Render challenge details.
    - [x] Render challenge description with correct formatting.

**Comment by danielduffield** [comment]
![codewars-solutions-issue-6-wireframe](https://user-images.githubusercontent.com/29046343/30291231-0a010290-96e7-11e7-9983-06b0346f9e16.png)
