### ISSUE TITLE
User can revisit the challenge list to view all previously submitted challenges.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/codewars-solutions#9]
# Motivation

The app should persist data so that users can create a list of completed challenges for display.

# Tasks

- [x] Create SQL migrations:
    - [x] Install pg-bump as a dependency.
    - [x] Create a migration to create the challenges table.
    - [x] Create migrations for the insertion of the first two rows.
- [x] Set the challenge list using the results of a SQL query:
    - [x] Update the redux store:
        - [x] Change the default challenges property in state to an empty array.
        - [x] Create a handler for action type 'LOADED_CHALLENGE_LIST'.
    - [x] Update the ChallengeList component:
        - [x] Create a componentDidMount method to fetch the challenge list.
        - [x] Dispatch a 'LOADED_CHALLENGE_LIST' with fetched challenge list data.
- [x] Handle added challenges:
    - [x] Insert a row into the challenges table with added challenge data.
